### ISSUE TITLE
Any idea on how to make an Axios request from this system? It is blocked.

### ISSUE THREAD

**Issue by aldomonteiro** [thEpisode/whatsapp-bot#2]
Hi,

Is it possible to implement an Axios request into this system? I tried, but it is blocked.

Into the sendMessage Function, I am trying to run this code:

```javascript
function sendMessage(id, msgReceived) {
  if (!id) {
    return
  }

  let Chats = Store.Chat.models
  let contact = id

  const url = 'https://url.ngrok.io/whatsapp'
  axios.post(url, {
    contact: contact,
    message: msgReceived
  }).then(function (response) {
    console.log(response)
  }).catch(function (error) {
    console.log(error.response);
  })
```

But, the connection is refused, show the error below:

whatsapp-bot/node_modules/axios/lib/adapters/xhr.js:178 Refused to connect to 'https://url.ngrok.io/whatsapp' because it violates the following Content Security Policy directive: "connect-src *.facebook.com facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' https://*.whatsapp.net https://www.facebook.com https://*.giphy.com https://*.tenor.co https://crashlogs.whatsapp.net/wa_clb_data https://crashlogs.whatsapp.net/wa_fls_upload_check https://www.bingapis.com/api/v6/images/search wss://*.web.whatsapp.com wss://web.whatsapp.com https://dyn.web.whatsapp.com".

**Comment by thEpisode** [comment]
Hi @aldomonteiro this problem is because your code is executed in whatsapp web and the website and their API's block any request to the world. I suggest you need to emit a message to Electron and use Axios in the "code behind". For example:

**renderer.js**
```
function sendMessage(id, msgReceived) {
  if (!id) {
    return
  }

  let Chats = Store.Chat.models
  let contact = id

  ipc.send('some-action', {...})
}
```

**main.js**
```
....
  ipc.on('whatsapp-is-ready', function (event, args) {
    event.sender.send('setup-bridge')
  })

  ipc.on('some-action', function (event, args) {
    // Your axios code
  })
....
```

**Comment by aldomonteiro** [comment]
Hi @thEpisode , that is exact what I was looking for! I apologize for the newbie question, but I didn't know how electron works before see your project. Thanks a lot.

**Comment by thEpisode** [comment]
You're welcome and no worries, we are very happy you're using our code!
