### ISSUE TITLE
How can I utilize this ??

### ISSUE THREAD

**Issue by zsubzwary** [thEpisode/whatsapp-bot#3]
A nice README guide on how to use this will be awesome, a getting started guide !!

**Comment by thEpisode** [comment]
Sure! I will be improve the readme, thanks! 

Quick advance: 

1. Run the app (npm start)
2. Log in with account (A) you want (web whatsapp is loaded)
3. Send a message from another account (B) to this account (A)
4. Account (A) reply a dummy message
5. Your work, include a library to use NLP o something bot messaging system.
