### ISSUE TITLE
Full size image

### ISSUE THREAD

**Issue by Gobestvini** [thEpisode/whatsapp-bot#6]
Hi, how can I get the full size image (from bot) ?

Thx

**Comment by thEpisode** [comment]
Hi, yes, if an user trying to send an image you can receive a base64 string. Another alternative is gather where is the location of image and get the blob file, load in memory and save it. Tell me if answer satisfy your needs, if not, please explain more to add in the next tasks

**Comment by Gobestvini** [comment]
Yes, thank you very much, I understand.
During this time there was another question, how can I send an image to a user? I tried to load an image into the input field, but it didn’t work out for me, maybe it is possible through drag and drop?

Thx

**Comment by thEpisode** [comment]
Umm I'm not trying to send it, these will be a new task ✌
